apiVersion: v1
kind: Service
metadata:
  name: "reefer-simulator"
  labels:
    app.kubernetes.io/part-of: refarch-kc
{{ include "kcontainer-reefer-simulator.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "kcontainer-reefer-simulator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
